spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dropify?createDatabaseIfNotExist=true
    username: root
    password: Rishabh@05#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: dropify

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    com.netflix: DEBUG

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000

servlet:
  multipart:
    enabled: true
    max-file-size: 2MB   # Maximum file size allowed per upload
    max-request-size: 2MB 

upload:
 dir: C:\Users\mobitino\Desktop\dropify\images